with open(r'D:\ue-ai\smart_ue_assistant\MCPServer\src\unreal_agent_mcp\__main__.py', 'w', encoding='utf-8') as f:
    f.write('"""Entry point for the Smart UE Assistant MCP Server."""\n')
    f.write('import os\nimport sys\n\n\ndef main():\n')
    f.write('    from .server import mcp\n')
    f.write('    from .tools import project, assets, world, actors, viewport, python, editor, knowledge, materials\n')
    f.write('    from .tools import context, properties\n')
    f.write('    from .tools import blueprints, asset_manage\n')
    f.write('    from .tools import screenshots, events\n')
    f.write('    from .tools import build\n')
    f.write('    from .tools import rag\n')
    f.write('    from .tools import batch_ops\n')
    f.write('    from .tools import scene_analysis\n')
    f.write('    mode = os.environ.get("SMART_UE_MODE", "stdio")\n')
    f.write('    if mode == "http":\n        _run_http()\n')
    f.write('    elif mode == "both":\n        _run_both(mcp)\n')
    f.write('    else:\n        mcp.run(transport="stdio")\n\n\n')
    f.write('def _run_http():\n')
    f.write('    try:\n        from .http_server import run_http_server\n        run_http_server()\n')
    f.write('    except ImportError:\n        print("http_server not implemented", file=sys.stderr)\n        sys.exit(1)\n\n\n')
    f.write('def _run_both(mcp):\n')
    f.write('    import threading\n')
    f.write('    try:\n        from .http_server import run_http_server\n')
    f.write('        threading.Thread(target=run_http_server, daemon=True).start()\n')
    f.write('    except ImportError:\n        pass\n')
    f.write('    mcp.run(transport="stdio")\n\n\n')
    f.write('if __name__ == "__main__":\n    main()\n')
print('done')
